language: node_js
node_js:
  - "12"

services:
  - docker

after_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t wdamtb/ci-app:latest .
  - docker push wdamtb/ci-app:latest

branches:
  only:
    - 12-travis-ci
