version: "3"

services:
  wordpress:
    container_name: wordpress
    image: wordpress:4.2.2
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: example
    ports:
      - "8080:80"

  db:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
