version: '3.1'

services:
  redmine:
    image: redmine:alpine
    restart: always
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_MYSQL: mysql
      REDMINE_DB_PASSWORD: example
      REDMINE_DB_ENCODING: utf8mb4
      REDMINE_SECRET_KEY_BASE: supersecretkey
    volumes:
      - ~/rep/docker-demo/redmine:/usr/src/redmine/files

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ~/rep/docker-demo/mysql:/var/lib/mysql
